[theme]
base = "light"
primaryColor = "#0E8388"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
